### ISSUE TITLE
what did they do?

### ISSUE THREAD

**Issue by NoobLikesThis** [icomplaintoomuch/UNCENSORED-FLAGS#1]

**Comment by icomplaintoomuch** [comment]
they decided to say "give us boosts for fflags" and on top of that they give early fflags to people that boost them, they say "early fflags on our discord" and yet its behind a paywall

**Comment by icomplaintoomuch** [comment]
they legit blocked me from making issues on their repository

**Comment by icomplaintoomuch** [comment]
these morons need to be taught respect

**Comment by NoobLikesThis** [comment]
o they did to me aswell
